### ISSUE TITLE
Page threw exception during rendering

### ISSUE THREAD

**Issue by mdchafin** [radzenhq/radzen-blazor-studio#5]
C:\Development\Git\PCT\Web\PCT\Pages\Account.razor(924,3607): error CS7036: There is no argument given that corresponds to the required formal parameter 'node' of 'Discount.Discount(NodeWrapper)'
C:\Development\Git\PCT\Web\PCT\Pages\Account.razor(924,3978): error CS7036: There is no argument given that corresponds to the required formal parameter 'node' of 'AddOn.AddOn(NodeWrapper)'
C:\Development\Git\PCT\Web\PCT\Pages\Account.razor(924,9178): error CS7036: There is no argument given that corresponds to the required formal parameter 'node' of 'Discount.Discount(NodeWrapper)'
C:\Development\Git\PCT\Web\PCT\Pages\Account.razor(924,9549): error CS7036: There is no argument given that corresponds to the required formal parameter 'node' of 'AddOn.AddOn(NodeWrapper)'

   at Radzen.Server.ProjectContext.Compile(Compilation compilation, AssemblyLoadContext context) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectContext.cs:line 120
   at Radzen.Server.ProjectServer.Compile(String fileName, String source, RazorProjectEngine projectEngine) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 778
   at Radzen.Server.ProjectServer.CompilePage(String fileName, String source, RazorProjectEngine engine) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 328
   at Radzen.Server.ProjectServer.Render(String fileName, String source) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 397
   at Radzen.Server.ProgramController.Render(RenderRequest request) in /Users/korchev/github/radzen-next/Radzen.Server/ProgramController.cs:line 305

**Comment by akorchev** [comment]
We would need access to the actual app if possible in order to troubleshoot.

**Comment by mdchafin** [comment]
Just scaffold out a WASM from VS 2022.

**Comment by akorchev** [comment]
A scaffolded WASM application seems to work fine with the latest version 1.0.0.preview.7.
