### ISSUE TITLE
Opening Page

### ISSUE THREAD

**Issue by sverduyn** [radzenhq/radzen-blazor-studio#18]
I created a new Blazor Server application. The _Imports.razor is created in the root folder but Blazor Studio is looking for it in the Shared Folder.
D:\Temp\Testing\RadzenStudioTest\RadzenStudioTest\_Imports.razor(10,24): error CS0234: The type or namespace name 'Shared' does not exist in the namespace 'RadzenStudioTest' (are you missing an assembly reference?)

   at Radzen.Server.ProjectContext.Compile(Compilation compilation, AssemblyLoadContext context) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectContext.cs:line 121
   at Radzen.Server.ProjectServer.Compile(String fileName, String source, RazorProjectEngine projectEngine) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 782
   at Radzen.Server.ProjectServer.CompilePage(String fileName, String source, RazorProjectEngine engine) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 329
   at Radzen.Server.ProjectServer.Render(String fileName, String source) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 398
   at Radzen.Server.ProgramController.Render(RenderRequest request) in /Users/korchev/github/radzen-next/Radzen.Server/ProgramController.cs:line 306

**Comment by akorchev** [comment]
> The _Imports.razor is created in the root folder but Blazor Studio is looking for it in the Shared Folder.

Radzen Blazor Studio shouldn't look for this file at all. Can you attach the application so we can test it?

**Comment by sverduyn** [comment]
[RadzenStudioTest.zip](https://github.com/radzenhq/radzen-blazor-studio/files/8402890/RadzenStudioTest.zip)

**Comment by akorchev** [comment]
I am able to open the attached application without problems. Does it work with the latest version 1.0.0.preview.7?

**Comment by sverduyn** [comment]
It works now with preview 7 thanks!!

Kind regards,

Shaun Verduyn  |  IT Support Consultant
T: +27 87 164 5000  |  M: +27 83 709 7846  |  ***@***.******@***.***>  |  www.mgfx.co.za<http://www.mgfx.co.za>
***@***.***
